name: RPGBookshelves
version: ${project.version}
main: es.mithrandircraft.rpgbookshelves.RPGBookshelves
api-version: 1.13
authors: [__Mithrandir__]
description: Improve your bookshelves with extra book storing features.
website: www.mithrandircraft.es
